/**
 * Generated by tsnapi — public API snapshot of `iframe-pane`
 */
// #region Interfaces
export interface IframePane {
  readonly id: string;
  readonly element: HTMLElement;
  readonly iframe: HTMLIFrameElement;
  readonly target: Element | null;
  readonly isMounted: boolean;
  readonly isVisible: boolean;
  readonly isDisposed: boolean;
  readonly lastActiveAt: number;
  mount: (_: Element) => void;
  unmount: () => void;
  show: () => void;
  hide: () => void;
  update: () => void;
  dispose: () => void;
}
export interface IframePaneOptions {
  tagName?: string;
  element?: HTMLElement;
  src?: string;
  attrs?: Record<string, string>;
  style?: IframePaneStyle;
  styleActive?: IframePaneStyle;
  styleHidden?: IframePaneStyle;
  onCreated?: (_: HTMLElement) => void;
}
export interface IframePanes {
  list: () => IframePane[];
  get: (_: string) => IframePane | undefined;
  has: (_: string) => boolean;
  ensure: (_: string, _?: IframePaneOptions) => IframePane;
  maxPanes: number;
  readonly isPointerLocked: boolean;
  lockPointerEvents: () => () => void;
  updateAll: () => void;
  readonly container: HTMLElement | undefined;
  readonly isDisposed: boolean;
  dispose: () => void;
}
export interface IframePanesOptions {
  document?: Document;
  container?: HTMLElement;
  maxPanes?: number;
  styleDefault?: IframePaneStyle;
  styleActive?: IframePaneStyle;
  styleHidden?: IframePaneStyle;
  zIndex?: number | string;
  onPaneCreated?: (_: IframePane) => void;
  onPaneDisposed?: (_: IframePane) => void;
}
// #endregion

// #region Types
export type IframePaneStyle = Record<string, string>;
// #endregion

// #region Functions
export declare function createIframePanes(_?: IframePanesOptions): IframePanes;
// #endregion