/**
 * Generated by tsnapi — public API snapshot of `iframe-pane`
 */
// #region Interfaces
export interface IframePane<E extends HTMLElement = HTMLIFrameElement> {
  readonly id: string;
  readonly element: E;
  readonly iframe: PaneIframe<E>;
  readonly target: Element | null;
  readonly isMounted: boolean;
  readonly isVisible: boolean;
  readonly isDisposed: boolean;
  readonly lastActiveAt: number;
  mount: (_: Element) => void;
  unmount: () => void;
  show: () => void;
  hide: () => void;
  update: () => void;
  dispose: () => void;
}
export interface IframePaneOptions<E extends HTMLElement = HTMLIFrameElement> {
  tagName?: string;
  element?: E;
  src?: string;
  attrs?: Record<string, string>;
  style?: IframePaneStyle;
  styleActive?: IframePaneStyle;
  styleHidden?: IframePaneStyle;
  onCreated?: (_: E) => void;
}
export interface IframePanes {
  list: () => IframePane<HTMLElement>[];
  get: (_: string) => IframePane<HTMLElement> | undefined;
  has: (_: string) => boolean;
  ensure: {
    <E extends HTMLElement>(_: string, _: Omit<IframePaneOptions<E>, 'element'> & {
      element: E;
    }): IframePane<E>;
    <K extends keyof HTMLElementTagNameMap>(_: string, _: Omit<IframePaneOptions<HTMLElementTagNameMap[K]>, 'tagName'> & {
      tagName: K;
    }): IframePane<HTMLElementTagNameMap[K]>;
    (_: string, _?: IframePaneOptions<HTMLIFrameElement>): IframePane<HTMLIFrameElement>;
  };
  maxPanes: number;
  readonly isPointerLocked: boolean;
  lockPointerEvents: () => () => void;
  updateAll: () => void;
  readonly container: HTMLElement | undefined;
  readonly isDisposed: boolean;
  dispose: () => void;
}
export interface IframePanesOptions {
  document?: Document;
  container?: HTMLElement;
  maxPanes?: number;
  styleDefault?: IframePaneStyle;
  styleActive?: IframePaneStyle;
  styleHidden?: IframePaneStyle;
  zIndex?: number | string;
  onPaneCreated?: (_: IframePane<HTMLElement>) => void;
  onPaneDisposed?: (_: IframePane<HTMLElement>) => void;
}
// #endregion

// #region Types
export type IframePaneStyle = Record<string, string>;
export type PaneIframe<E extends HTMLElement> = [E] extends [HTMLIFrameElement] ? HTMLIFrameElement : [HTMLElement] extends [E] ? HTMLIFrameElement | undefined : undefined;
// #endregion

// #region Functions
export declare function createIframePanes(_?: IframePanesOptions): IframePanes;
// #endregion